extends Node

var words = [
	"Toxic Troll",
	"Griefer",
	"Salty-saboteur",
	"Rage-quitter",
	"Flame-thrower",
	"Feed-machine",
	"Tilt-master",
	"Negative-nancy",
	"Drama-king",
	"Blamer",
	"Scoreboard-stalker",
	"Afk-abuser",
	"Trash-talker",
	"Downer",
	"Rager",
	"Noob-basher",
	"Morale-biller",
	"Doom-prophet",
	"Salt-spreader",
	"Abuse-hound",
	"Tilt-magnet",
	"Feeder",
	"Salt-mine",
	"Drama-llama",
	"Salt-lord",
	"Poison-player",
	"Complain-train",
	"Quitter",
	"Saboteur",
	"Sourpuss",
	"Salt-shaker",
	"Tilt-factory",
	"Balls",
	"Flame-machine",
	"Grief-beast",
	"Detriment",
	"Feed-bot",
	"Toxic-twit",
	"Whiner",
	"Grief-grinder",
	"Bad-vibe",
	"Killjoy",
	"Salt-queen",
	"Buzzkill",
	"Rage-cannon",
	"Trouble-maker",
	"Rage-king",
	"Mood-killer",
	"Blame-game",
	"Salt-goblin",
	"Negatron",
	"Agitator",
	"Meltdown",
	"Drama-bomb",
	"Salt-geyser",
	"Flame-kid",
	"Trouble-magnet",
	"Negative-nellie",
	"Salt-sprinkler",
	"Downer-debbie",
	"Flame-warper",
	"Gripe-master",
	"Aggravator",
	"Salt-master",
	"Blame-shifter",
	"Flame-king",
	"Sad-sack",
	"Stress-test",
	"Rage-blaster",
	"Complain-queen",
	"Rage-beast",
	"Sad-sapper",
	"Gripe-guru",
	"Killjoy-kid",
	"Bummer",
	"Salt-spread",
	"Salt-bringer",
	"Drama-duchess",
	"Blame-shamer",
	"Frustration-fuel",
	"Naysayer",
	"Blight",
	"Salt-fountain",
	"Blame-guru",
	"Flame-throw",
	"Complainer",
	"Stressor",
	"Tilt-turner",
	"Salt-sprayer",
	"Downer-dave",
	"Grump",
	"Agony-agent",
	"Trouble-trigger",
	"Misery-maker",
	"Salt-dispenser",
	"Grief-spreader",
	"Buzz-killer",
	"Drama-dealer",
	"Trouble-tank",
	"Rage-reactor"
]

func get_prompt() -> String:
	var word_index = randi() % words.size()
	
	var word = words[word_index]
	
	var actual_word = word.substr(0, 1).to_lower() + word.substr(1).to_lower()
	
	
	return actual_word
